name: vt_challenge
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.9.24
  - certifi=2024.8.30
  - cudatoolkit=11.3.1
  - ffmpeg=4.3
  - freetype=2.12.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - intel-openmp=2023.1.0
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.40
  - lerc=3.0
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.10
  - mkl_random=1.2.7
  - ncurses=6.4
  - nettle=3.7.3
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.0.15
  - pillow=10.4.0
  - pip=24.2
  - pysocks=1.7.1
  - python=3.9.20
  - pytorch=1.12.1
  - pytorch-mutex=1.0
  - readline=8.2
  - requests=2.32.3
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tbb=2021.8.0
  - tk=8.6.14
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - typing_extensions=4.11.0
  - urllib3=2.2.3
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - bleach==6.2.0
      - charset-normalizer==3.4.0
      - clarabel==0.9.0
      - click==8.1.7
      - colorama==0.4.6
      - cvxpy==1.5.3
      - docker-pycreds==0.4.0
      - ecos==2.0.14
      - filelock==3.16.1
      - fsspec==2024.10.0
      - ftfy==6.3.1
      - gitdb==4.0.11
      - gitpython==3.1.43
      - huggingface-hub==0.26.2
      - idna==3.10
      - joblib==1.4.2
      - kaggle==1.6.17
      - lightning-utilities==0.11.8
      - numpy==1.26.4
      - open-clip-torch==2.29.0
      - osqp==0.6.7.post3
      - packaging==24.1
      - pandas==2.2.3
      - platformdirs==4.3.6
      - protobuf==5.28.3
      - psutil==6.1.0
      - python-dateutil==2.9.0.post0
      - python-slugify==8.0.4
      - pytz==2024.2
      - pyyaml==6.0.2
      - qdldl==0.1.7.post4
      - regex==2024.9.11
      - safetensors==0.4.5
      - scikit-learn==1.5.2
      - scipy==1.13.1
      - scs==3.2.7
      - sentry-sdk==2.17.0
      - setproctitle==1.3.3
      - six==1.16.0
      - smmap==5.0.1
      - tabulate==0.9.0
      - text-unidecode==1.3
      - threadpoolctl==3.5.0
      - timm==1.0.11
      - torchmetrics==1.5.1
      - tqdm==4.66.6
      - tzdata==2024.2
      - wandb==0.18.5
      - wcwidth==0.2.13
      - webencodings==0.5.1
